config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # display task form
  get 'tasks/new', to: 'tasks#new', as: :new_task

  # list all tasks
  get 'tasks', to: 'tasks#index'

  #submiting the form
  post 'tasks', to: 'tasks#create'

  get 'tasks/:id/edit', to: 'tasks#edit', as: :task_edit

  patch 'tasks/:id', to: 'tasks#update'

  # task details
  get 'tasks/:id', to: 'tasks#show', as: :task

  #destroy
  delete 'tasks/:id', to: "tasks#destroy", as: :task_delete

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def new
    @task = Task.new
  end

  def create
     @task = Task.new(task_params)
     @task.save
     redirect_to task_path(@task)
  end

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
    # @title = Task.find(params[:id]).title
    # @details = Task.find(params[:id]).details
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= form_for(@task) do |t| %>
  <%= t.label :title %>
  <%= t.text_field :title %>
  <%= t.label :details %>
  <%= t.text_field :details %>
  <%= t.label :completed %>
  <%= t.check_box :completed %>
  <%= t.submit %>
<% end %>

app/views/tasks/index.html.erb
<ul>
  <% @tasks.each do |task| %>
    <li><%= link_to task.title, task_path(task) %>
    <%= link_to "Delete",
            task_path(task.id),
            method: :delete,
            data: { confirm: "Are you sure?" } %>
<a data-confirm="Are you sure?" rel="nofollow" data-method="delete" href="/tasks/2">
</a>
</li>
  <% end %>
</ul>

<p><%= link_to "Add new one", new_task_path  %></p>

app/views/tasks/new.html.erb
<%= form_for(@task) do |t| %>
  <%= t.label :title %>
  <%= t.text_field :title %>
  <%= t.label :details %>
  <%= t.text_field :details %>
  <%= t.label :completed %>
  <%= t.check_box :completed %>
  <%= t.submit %>
<% end %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>
<p><%= @task.details %></p>

<p><%= link_to "Edit task", task_edit_path  %></p>